### ISSUE TITLE
What should dynamic BitFlags look like?

### ISSUE THREAD

**Issue by sairus7** [jmert/BitFlags.jl#12]
I want to read a bunch of bit mask names and codes from a file at runtime and construct a collection of such flags. What should it be? A dict or a tuple? Wrapped into a PooledArray or similar container?

**Comment by jmert** [comment]
Since this package constructs types to represent a set of flags, I think your only option would be to `eval` an `Expr` containing the definitions. (Unless I'm missing what you mean.) That's more of a general Julia question than something specific to this package, though.

**Comment by sairus7** [comment]
You are right, this is not a question about this particular package, but rather a general question about how to make a dynamic enum.
