### ISSUE TITLE
Scoped Names

### ISSUE THREAD

**Issue by baumgold** [jmert/BitFlags.jl#13]
Thank you for this package.  Unfortunately it has a drawback that the names for instances are not scoped. This means, for example, that it is inconvenient to use "common" names for BitFlag instances, and it is impossible to have multiple BitFlags with the same instance names.  Can this package be refactored to accommodate such a structure?  The implementation could be similar to that of [EnumX.jl](https://github.com/fredrikekre/EnumX.jl).

**Comment by jmert** [comment]
@baumgold I know it's been a long wait, but #15 just added the ability to create scoped bit flags with a new `@bitflagx` macro. I'll be tagging a new 0.1.8 release shortly.
